import "./globals.css";
import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import { Header } from "./Header";
import AppProvider from "./provider";
import NextAuthProvider from "./providers/NextAuth";


const inter = Noto_Sans_JP({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
      <NextAuthProvider>
        <AppProvider>
          <Header />
          {children}
        </AppProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
